fix: remove graphql version dependency
github/graphql-client pull request #286
Opened 2022-02-26 01:05 UTC by srgoldman

The graphql gem version was locked to version 1. Per Robert's suggestion, I simply removed it from the gemspec.

2022-03-14 16:10 UTC, knapo requested changes

2022-03-14 21:31 UTC, srgoldman commented on graphql-client.gemspec
> -  s.add_dependency "graphql", "~> 1.10"
ok, that makes sense. updated so it will include the current major release.

2022-03-15 09:25 UTC, udl commented on graphql-client.gemspec
> -  s.add_dependency "graphql", "~> 1.10"
Does it really need v1? In our case we would need it in combination with the new v2 graphql gem...

2022-03-15 10:39 UTC, KuIvan commented
Hi @rmosolgo , when will you accept this PR?

2022-03-15 13:06 UTC, rmosolgo commented
I don't have write permission to this project anymore -- I used to work at GitHub, but I now don't.

2022-03-15 14:52 UTC, gjtorikian commented
I just removed myself as an owner for them gem because I also don't work at GitHub anymore, and can't merge this PR. In fact, none of those mentioned usernames work there anymore.

I can't think of anyone still at GitHub who is part of the team that manages this, so I think your best bet might be to ask at https://support.github.com. Good luck. ✌️

2022-03-15 20:35 UTC, knapo commented
and maybe @jhawthorn is able to help here ?

2022-03-17 14:21 UTC, v-kumar commented
@arthurschreiber @jhawthorn Any update here?

2022-04-12 19:39 UTC, imwiss approved these changes
Thanks for surfacing this to my attention, @rmosolgo. 

I discussed the changes with the team and they look good to us! Thanks @srgoldman.

2022-04-12 19:41 UTC, knapo approved these changes

2022-04-12 20:31 UTC, knapo commented
@imwiss Can we have it merged and new version released then ? 🙏

2022-04-13 15:52 UTC, imwiss commented
> @imwiss Can we have it merged and new version released then ? 🙏

Yes 🙂  I'm working on it and aim to have a new version released shortly. As you all noticed, this library has unfortunately not been actively maintained lately. The team at GitHub is trying to figure out next steps regarding ownership and maintainers but we wanted to prioritize unblocking users with this PR for now. Thank you all for your patience as we work on next steps.

2022-04-13 15:52 UTC, merged

2022-04-19 21:36 UTC, srgoldman commented
@imwiss Appreciate you pushing this over the finish line. Any update on getting the new version released?

2022-04-19 22:19 UTC, arthurschreiber commented
I'll see if I can get a new version released next week! 🙇‍♂️

2022-04-29 23:13 UTC, yutamgit commented
Hi, @arthurschreiber ! Thanks for helping us get this through. I just wanted to see how things are progressing.
When can we expect the release?
Thank you, and have a great weekend!

2022-05-02 15:22 UTC, v-kumar commented
@arthurschreiber Echoing @yutamgit Can we get a release? This little gem is blocking a lot of other gem upgrades.

2022-05-02 20:42 UTC, imwiss commented
Update: @arthurschreiber released a [new version](https://rubygems.org/gems/graphql-client/versions/0.18.0) today. Thanks for all your help, @arthurschreiber, and thank you everyone for your patience as we were digging into this!